[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "php82Packages.composer"]

[phases.install]
cmds = [
  "cd back && composer clear-cache",
  "cd back && rm -rf vendor composer.lock",
  "cd back && composer install --no-dev --optimize-autoloader --no-interaction"
]

[phases.build]
cmds = [
  "cd back && php artisan key:generate --force --no-interaction",
  "cd back && php artisan migrate --force --no-interaction",
  "cd back && php artisan db:seed --force --no-interaction"
]

[start]
cmd = "cd back && php artisan serve --host=0.0.0.0 --port=${PORT:-8000}"

