[phases.setup]
nixPkgs = ["php81", "php81Extensions.pdo", "php81Extensions.pdo_mysql", "php81Extensions.mbstring", "php81Packages.composer"]

[phases.install]
cmds = ["cd back && composer install --no-dev --optimize-autoloader --no-interaction --ignore-platform-reqs"]

[phases.build]
cmds = [
  "cd back && php artisan key:generate --force --no-interaction",
  "cd back && php artisan migrate --force --no-interaction",
  "cd back && php artisan db:seed --force --no-interaction"
]

[start]
cmd = "cd back && php artisan serve --host=0.0.0.0 --port=${PORT:-8000}"

